### ISSUE TITLE
App doesn't work with just numbers ...

### ISSUE THREAD

**Issue by daath** [10der/homeassistant-custom_components-awtrix#10]
I don't know if this is a quirk, but I am using this in an automation:

```
action: awtrix.awtrix_myclock_push_app_data
data:
  data:
    text: "KR {{ '{:.2f}'.format(states('sensor.energi_data_service')|round(2)) }}"
    lifetime: 1000
    duration: 5
    pushIcon: 2
    icon: "54077"
  name: elpris
```

If I remove "KR " from the text the value (a float) doesn't show - there has to be something at the beginning or the end of the text for it to show ... 

To be clear, the above works, but this does not work:

```
action: awtrix.awtrix_myclock_push_app_data
data:
  data:
    text: "{{ '{:.2f}'.format(states('sensor.energi_data_service')|round(2)) }}"
    lifetime: 1000
    duration: 5
    pushIcon: 2
    icon: "54077"
  name: elpris
```

**Comment by daath** [comment]
OK, this is not your issue - this is an AWTRIX bug: https://github.com/Blueforcer/awtrix3/issues/618

You can do a workarsound by concatenating a zero-width space:

```
action: awtrix.awtrix_myclock_push_app_data
data:
  data:
    text: "{{ '{:.2f}'.format(states('sensor.energi_data_service')|round(2)) ~ '​' }}"
    lifetime: 1000
    duration: 5
    pushIcon: 2
    icon: "54077"
  name: elpris
```
Note the ` ~ '​'`

**Comment by daath** [comment]
Well, Blueforcer seems to think it is your issue - maybe you need to cast the "text"-part of the MQTT payload to a string ...

EDIT: From what I can tell json.dumps sees a float/int in the value-part then it is converted to a number - but the "text"-part of the payload MUST be a string ...

EDIT2: Maybe:

```
if 'text' in payload:
    payload['text'] = str(payload['text'])
```
Before sending it to MQTT ...

My python is rusty, so ... :)

**Comment by daath** [comment]
I created a pull request to fix this issue :)

https://github.com/daath/homeassistant-custom_components-awtrix/compare/main...daath-patch-1

**Comment by daath** [comment]
I think I did something wrong with the pull request - I tried again :)

**Comment by apmillen** [comment]
This has broken the functionality of being able to display text in coloured fragments:
*https://blueforcer.github.io/awtrix3/#/api?id=display-text-in-colored-fragments**

```
text:
  - t: "47"
    c: FFFFFF
  - t: "Days"
    c: FF0000
icon: 97
```

So now instead of this showing "47" in white and "Days" in red" it shows "[{"t": "47", "c": "FFFFFF"}, {"t": "Days", "c": "FF0000"}]"
