### ISSUE TITLE
No icon shown with notification

### ISSUE THREAD

**Issue by naamah75** [10der/homeassistant-custom_components-awtrix#21]
I tried the example below, but no icons are shown along with the notification. Maybe I'm doing something wrong?

```
service: notify.awtrix_bedroom
data:
  message: The garage door has been open for 10 minutes.
  data:
    icon: "33655"
    sound: beep
```

**Comment by 10der** [comment]
r u sure what you succ download icon before?

<img width="769" alt="Image" src="https://github.com/user-attachments/assets/61c37c05-81c7-4663-b279-87690fb4901a" />

**Comment by 10der** [comment]
othwerwise
try

```
service: notify.awtrix_bedroom
data:
  message: The garage door has been open for 10 minutes.
  data:
    icon: "https://developer.lametric.com/content/apps/icon_thumbs/33655"
    sound: beep
```
